--
-- PostgreSQL database dump
--

-- Dumped from database version 14.4
-- Dumped by pg_dump version 14.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ToDoItems; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."ToDoItems" (
    "Id" integer NOT NULL,
    "Title" text,
    "Description" text,
    "CreatedTime" timestamp without time zone NOT NULL,
    "DoneTime" timestamp without time zone NOT NULL,
    "IsDone" boolean NOT NULL
);


ALTER TABLE public."ToDoItems" OWNER TO postgres;

--
-- Name: ToDoItems_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."ToDoItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ToDoItems_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: ToDoItems; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."ToDoItems" ("Id", "Title", "Description", "CreatedTime", "DoneTime", "IsDone") FROM stdin;
3	xbvvcxb	sdfgsdf	2022-07-11 11:29:06.750261	0001-01-01 00:00:00	f
1	gsfgfs	fghjfgh	2022-07-11 11:29:01.720496	2022-07-11 11:30:17.932983	t
2	wertwert	gfhjfghj	2022-07-11 11:29:03.808474	2022-07-11 11:30:18.864421	t
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20220711062757_InitialMigration	5.0.17
\.


--
-- Name: ToDoItems_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."ToDoItems_Id_seq"', 3, true);


--
-- Name: ToDoItems PK_ToDoItems; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."ToDoItems"
    ADD CONSTRAINT "PK_ToDoItems" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- PostgreSQL database dump complete
--

